name: Yarn Workflow
on:
  push:
    paths:
      - '/*'

jobs:
  build:
    name: Yarn Build
    runs-on: ubuntu-20.04
    steps:
      - name: Install yarn
        uses: actions/checkout@v2
